### ISSUE TITLE
Package options - can we bridge these from the API? 

### ISSUE THREAD

**Issue by NoobSkie** [NoobSkie/BaoPals#13]
Example: 
https://detail.tmall.com/item.htm?spm=a217h.7736145.1998561592.704.n15yfO&id=521716315869&scm=1029.minilist-17.1.1101&ppath=20000:11656&sku=20000:11656&sku_properties=5919063:6536025 

http://www.baopals.com/products/521716315869

**Comment by wuhuw** [comment]
it is showing packages there. isn't it?

**Comment by mrjaybird** [comment]
Our site shows buttons for different packages, but it doesn't show the details of those packages. It seems on Taobao the package details are shown in an image file. If we can bring that image to our site, it could be helpful to our shoppers.

**Comment by mrjaybird** [comment]
Here's the image from Tmall for that product: 
![computer-packages-image-from-tmall](https://cloud.githubusercontent.com/assets/15699121/12423320/daa48180-bf05-11e5-8a01-0ea5a500cb0e.jpg)

**Comment by wuhuw** [comment]
this is not in API at all,  ​


Best regards,

*Don *Zhou   *WuhuW   *Your Chinese Business Partner
*Q*Q: 93709529   *S*kype: weekwinter  *E*mail: www@wuhuw.com
*W*: www.wuhuw.com   *A*: A1807, Golden Plaza, Wuhu, Anhui. China
