### ISSUE TITLE
Incorrect Pricing for Discounts

### ISSUE THREAD

**Issue by mrjaybird** [NoobSkie/BaoPals#5]
When items have a discount on Taobao/Tmall, this discount price does not show on our site. Instead, our site shows the normal price. 

See this example: 
http://world.tmall.com/item/37015715387.htm?skuId=59788981681
http://www.baopals.com/products/37015715387

The price on our website should show RMB119, same as on Tmall.

**Comment by wuhuw** [comment]
fixed now , but it is not stable sometimes

**Comment by mrjaybird** [comment]
Hi Don,

Thanks for the quick response, although it seems there are still some areas
where this needs fixing. The price is correct in search results, but not
other pages. The correct price for the two Skyy vodka bottles is CNY64. You
can see this on the search results page and the Taobao page. However, on
the homepage featured product, on the product page, and on checkout, the
price is higher. Please see the attached screenshots.

Best,
Jay


On Wed, Nov 11, 2015 at 12:15 PM, wuhuw <notifications@github.com> wrote:

> fixed now , but it is not stable sometimes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NoobSkie/BaoPals/issues/5#issuecomment-155656594>.
>



-- 

*Jay Thornhill* | jay.thornhill@ile-china.com | +86 186 1623 1613

71 West Suzhou Road, 3/F  Shanghai 200041
IVY LEAGUE ENGLISH
常春藤商务英语
www.ile-china.com

**Comment by NoobSkie** [comment]
Actually regarding this i think i may know the issue, on our frontage products jay we are hand selecting them and if you see next to the item we also hand select the price its not automatically updated

**Comment by mrjaybird** [comment]
Okay, that solves the homepage issue then.

We still need the price to be consistent on all the other pages.

On Wed, Nov 11, 2015 at 1:19 PM, Tyler McNew <notifications@github.com>
wrote:

> Actually regarding this i think i may know the issue, on our frontage
> products jay we are hand selecting them and if you see next to the item we
> also hand select the price its not automatically updated
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NoobSkie/BaoPals/issues/5#issuecomment-155670263>.
>



-- 

*Jay Thornhill* | jay.thornhill@ile-china.com | +86 186 1623 1613

71 West Suzhou Road, 3/F  Shanghai 200041
IVY LEAGUE ENGLISH
常春藤商务英语
www.ile-china.com

**Comment by wuhuw** [comment]
search page should be consistent also, but today is special day,  we will
have to check back and see a few days later

**Comment by mrjaybird** [comment]
Don, to be clear - the search page is correct. The pricing is not correct
on the product page and all checkout pages. Please refer to the Skyy
screenshots to see.

Best,
Jay

On Wed, Nov 11, 2015 at 1:59 PM, wuhuw <notifications@github.com> wrote:

> search page should be consistent also, but today is special day, we will
> have to check back and see a few days later
>
> On Wed, Nov 11, 2015 at 1:37 PM, mrjaybird <notifications@github.com>
> wrote:
>
> > Okay, that solves the homepage issue then.
> >
> > We still need the price to be consistent on all the other pages.
> >
> > On Wed, Nov 11, 2015 at 1:19 PM, Tyler McNew <notifications@github.com>
> > wrote:
> >
> > > Actually regarding this i think i may know the issue, on our frontage
> > > products jay we are hand selecting them and if you see next to the item
> > we
> > > also hand select the price its not automatically updated
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/NoobSkie/BaoPals/issues/5#issuecomment-155670263>.
> > >
> >
> >
> >
> > --
> >
> > *Jay Thornhill* | jay.thornhill@ile-china.com | +86 186 1623 1613
> >
> > 71 West Suzhou Road, 3/F Shanghai 200041
> > IVY LEAGUE ENGLISH
> > 常春藤商务英语
> > www.ile-china.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/NoobSkie/BaoPals/issues/5#issuecomment-155672283>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NoobSkie/BaoPals/issues/5#issuecomment-155677705>.
>



-- 

*Jay Thornhill* | jay.thornhill@ile-china.com | +86 186 1623 1613

71 West Suzhou Road, 3/F  Shanghai 200041
IVY LEAGUE ENGLISH
常春藤商务英语
www.ile-china.com

**Comment by wuhuw** [comment]
but product pages have been updated already,  mostly should be fine.  but
we will have to see from tomorrow as taobao is limiting the calls on today


Best regards,

*Don *Zhou   *WuhuW   *Your Chinese Business Partner
*Q*Q: 93709529   *S*kype: weekwinter  *E*mail: www@wuhuw.com
*W*: www.wuhuw.com   *A*: A1807, Golden Plaza, Wuhu, Anhui. China
