### ISSUE TITLE
Customer reviews not being pulled

### ISSUE THREAD

**Issue by mrjaybird** [NoobSkie/BaoPals#6]
On many of our product pages, there are no customer reviews. However, these same products on Taobao have many customer reviews. They should be showing on our product pages. 

Example: 
http://item.taobao.com/item.htm?id=43359062082&spm=2014.21379799.0.0
http://www.baopals.com/products/43359062082

**Comment by wuhuw** [comment]
this is scrapped from taobao. it is not stable sometimes
